### ISSUE TITLE
unused parameters and keyword 'ignore'

### ISSUE THREAD

**Issue by RaphHaddad** [karimsa/gulp-jslint#38] opened 2016-12-14 03:10 UTC
Hello,

On [JSLint ](http://www.jslint.com/help.html) the ignore keyword is explained:

> JSLint introduces a new reserved word: ignore. It is used in parameter lists and in catch clauses to indicate a parameter that will be ignored. Unused warnings will not be produced for ignore.

However, when I use this keyword, I get an error telling me 

> Unused 'ignore'

![2016-12-14 12_59_07-administrator_ posh git healthnav task-27420](https://cloud.githubusercontent.com/assets/430909/21168247/9efee922-c206-11e6-97af-315c0f8e4b30.png)

The function in question is below:

`    form.each(function (ignore, element) {
    });
`

Am I missing something here?

Thanks for your help in advanced.

**Comment by karimsa** [comment] 2016-12-14 04:09
Hi, there:

It seems that this issue is a duplicate of #34.

The solution that I posted there was:

```javascript
(function () {
    'use strict';

    var test = [];

    /*jslint ignore:start*/
    test.forEach(function (elm, index) {
        return elm;
    });
    /*jslint ignore:false*/
}());
```

Though this isn't really to do with gulp-jslint but rather to do with JSLint itself. Due to this, I am closing this issue. But please feel free to ask more questions.

**Comment by RaphHaddad** [comment] 2016-12-14 04:39
Hey @karimsa 

Thanks for your response. I've tried testing the [JSLint](http://www.jslint.com/) website with test code and it seems to not throw a unused variable warning.

Take a look at my example here: https://github.com/RaphHaddad/jslint-ignore-test

If you copy and paste main.js content into the [JSLint](http://www.jslint.com/) website. You wont get any unused variables errors.

however, if you run JSLint from gulp you will get the errors

~~~
main.js
  line 5  col 28  Unused 'ignore'.

  ×  1 error  ‼  0 warning
~~~

**Comment by RaphHaddad** [comment] 2016-12-14 04:49
I'm happy to give you a hand here if you deem this issue as re-open :)

**Comment by karimsa** [comment] 2016-12-14 04:49
Yes, please. I'll update this issue if I find anything, but I'd appreciate the assistance as I'm quite busy this week.

**Closed** 2016-12-14 17:08 UTC
